name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifiez le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurez Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Étape 3 : Affichez Hello World
      - name: Display Hello World
        run: echo "Hello World"

      # Étape 4 : Vérifiez la build (si applicable)
      - name: Run tests
        run: |
          python -m unittest discover -s tests
